cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
  paths:
    - .composer/
    - .php_cs.cache

variables:
  COMPOSER_CACHE_DIR: ".composer"
  TYPO3_PATH_WEB: "$CI_PROJECT_DIR/.Build/Web"
  MYSQL_DATABASE: "typo3"
  MYSQL_ROOT_PASSWORD: "joh316"
  typo3DatabaseName: "typo3"
  typo3DatabaseHost: "mysql"
  typo3DatabaseUsername: "root"
  typo3DatabasePassword: "joh316"

before_script:
  - apk add git --update

stages:
  - cgl
  - typoscript
  - yaml
  - test
  - upload

cgl:cs-php:
  image: composer:1.6
  stage: cgl
  before_script:
    - composer remove typo3/cms-core --no-update
    - composer install --no-progress --no-ansi --no-interaction
  script:
    - .Build/bin/php-cs-fixer fix --config=Build/.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection ./

cgl:php72:
  stage: cgl
  image: php:7.2-alpine
  script:
    - find . -name \*.php -exec php -l "{}" \;

cgl:php73:
  stage: cgl
  image: php:7.3-alpine
  script:
    - find . -name \*.php -exec php -l "{}" \;

cgl:php74:
  stage: cgl
  image: php:7.4-alpine
  script:
    - find . -name \*.php -exec php -l "{}" \;

typoscript:test:
  stage: typoscript
  image: composer:1.6
  script:
    - composer remove typo3/cms-core --no-update
    - composer install --no-progress --no-ansi --no-interaction
    - .Build/bin/typoscript-lint -c Build/tslint.yaml

yaml:test:
  stage: yaml
  image: python:alpine3.7
  before_script:
    - pip install yamllint==1.10.0
  script:
    - yamllint -c Build/yamllint.yaml Configuration/ Resources/

.test: &test_php
  stage: test
  services:
    - mysql:5
  image: php:$DOCKER_TAG
  only:
    - branches
  before_script:
    - apk add --no-cache bash curl git mercurial openssh openssl parallel subversion tini
    - >
      if [[ "$COVERAGE" == "1" ]]; then
        apk add --no-cache $PHPIZE_DEPS
        pecl install xdebug && docker-php-ext-enable xdebug
      fi
    - docker-php-ext-install mysqli
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --no-ansi --install-dir=/usr/bin --filename=composer
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - composer require typo3/cms-core="${TYPO3_VERSION}"
  script:
    - >
      if [[ "$COVERAGE" == "0" ]]; then
        .Build/bin/phpunit --coverage-text --colors=never --testdox -c Build/UnitTests.xml Tests/Unit
      fi
    - >
      if [[ "$COVERAGE" == "1" ]]; then
        .Build/bin/phpunit --coverage-text --colors=never --coverage-clover=phpunit.coverage.xml --log-junit=phpunit.report.xml --testdox -c Build/UnitTests.xml Tests/Unit
      fi
  #    - find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'
  artifacts:
    paths:
      - phpunit.coverage.xml
      - phpunit.report.xml
    expire_in: 1 day
    when: always

# Build in PHP 7.2 and TYPO3 9.5
test:php72:typo3_9:
  <<: *test_php
  variables:
    DOCKER_TAG: 7.2-alpine
    TYPO3_VERSION: ^9.5
    COVERAGE: 0

# Build in PHP 7.3 and TYPO3 9.5
test:php73:typo3_9:
  <<: *test_php
  variables:
    DOCKER_TAG: 7.3-alpine
    TYPO3_VERSION: ^9.5
    COVERAGE: 0

# Build in PHP 7.4 and TYPO3 9.5
test:php74:typo3_9:
  <<: *test_php
  variables:
    DOCKER_TAG: 7.4-alpine
    TYPO3_VERSION: ^9.5
    COVERAGE: 1

ter-upload:
  image: php:7.3-alpine
  stage: upload
  #only:
  #  - tags
  #when: manual
  before_script:
    - apk --no-cache add git libzip-dev libxml2-dev
    - docker-php-ext-install mbstring zip soap
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - export COMPOSER_CACHE_DIR=.composer
  script:
    - composer install --no-progress --no-ansi --no-interaction
    - composer require namelesscoder/typo3-repository-client
    - export TYPO3_PATH_WEB="$PWD/.Build/Web"
    - >
      if [ -n "$Releas" ] && [ -n "$TerUsername" ] && [ -n "$TerPassword" ]; then
        echo -e "Preparing upload of release ${Releas} to TER mit ${TerUsername} und ${TerPassword}\n"
        # Cleanup before we upload
      #  git reset --hard HEAD && git clean -fx
        # Upload
        TAG_MESSAGE="git tag -n10 -l $Releas | sed 's/^[0-9.]*[ ]*//g'"
        echo "Uploading release ${Releas} to TER mit ${TAG_MESSAGE}"
       # .Build/bin/upload . "$TerUsername" "$TerPassword" "$TAG_MESSAGE"
      fi;

