version: '3.6'

services:
  web:
    volumes:
      - "~/.composer/cache/:/home/.composer/cache/"
    environment:
      - TYPO3_CONTEXT=Development
      - TYPO3_INSTALL_DB_DRIVER=mysqli
      - TYPO3_INSTALL_DB_USER=db
      - TYPO3_INSTALL_DB_PASSWORD=db
      - TYPO3_INSTALL_DB_HOST=db
      - TYPO3_INSTALL_DB_PORT=3306
      - TYPO3_INSTALL_DB_UNIX_SOCKET=
      - TYPO3_INSTALL_DB_USE_EXISTING=1
      - TYPO3_INSTALL_DB_DBNAME=db
      - TYPO3_INSTALL_ADMIN_USER=admin
      - TYPO3_INSTALL_ADMIN_PASSWORD=typo3graf
      - TYPO3_INSTALL_SITE_NAME=$DDEV_SITENAME (on DDEV)
      - TYPO3_INSTALL_SITE_SETUP_TYPE=no
      - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
